### ISSUE TITLE
Research Tools for Project

### ISSUE THREAD

**Issue by nnrogers515** [nnrogers515/RealScript#3]
Many tools are utilized in the project and researching them now will benefit us in the future. Specifically, we should focus on Websockets, React.js and LogRocket.

=========================

Tasks:
- [x] Research into Websockets
- [x] Tutorial for React.js if Needed
- [x] Research LogRocket
- [x] Research the other tools that may cause issues
- [x] Compile a list of resources for the tools

**Comment by nnrogers515** [comment]
Websockets:
- https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API
- https://www.geeksforgeeks.org/what-is-web-socket-and-how-it-is-different-from-the-http/

React.js:
- (Their tutorial is probably best) https://reactjs.org/tutorial/tutorial.html

LogRocket (There isn't a lot on this tool outside of their website):
- https://logrocket.com/
- https://www.youtube.com/watch?v=UWpzJ7bqoF8

Resources for the other tools (For ease of access):
- Webcanvas API
  - https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API
- Node.js (Setup and Tutorial)
  - https://code.visualstudio.com/docs/nodejs/nodejs-tutorial
  - https://www.tutorialspoint.com/nodejs/nodejs_environment_setup.htm
- Simple-Peer Library
  - https://developer.aliyun.com/mirror/npm/package/simple-peerjs
  - https://github.com/feross/simple-peer
- WS (Websocket Library)
  - https://github.com/websockets/ws
  - https://www.pubnub.com/blog/nodejs-websocket-programming-examples/
- Webtorrent
  - https://www.npmjs.com/package/webtorrent
  - https://webtorrent.io/intro
  - https://webtorrent.io/docs
- NGINX
  - http://nginx.org/en/docs/beginners_guide.html
  - http://tutorials.jenkov.com/nginx/index.html
- Cognito & AWS
  - https://medium.com/@prasadjay/amazon-cognito-user-pools-in-nodejs-as-fast-as-possible-22d586c5c8ec
  - https://aws.amazon.com/blogs/mobile/amazon-cognito-in-your-node-js-web-app/
  - https://aws.amazon.com/getting-started/hands-on/
  - (Linkedin Learning Free with School Account) https://www.linkedin.com/learning/topics/amazon-web-services?accountId=43607124&u=43607124&success=true&authUUID=JfGqylLuRQmxHZjKHUaYvw%3D%3D

**Comment by GabriellaXue** [comment]
This is amazing!!! Thanks for doing all the researches!!!
